#!/usr/bin/env python3
"""Vendor the JSON Schemas the editor checks common configuration files with.

Each schema is downloaded from where it is published, checked to be JSON,
and written here with LF line endings; catalog.toml says which files each one
is for, and README.md is regenerated with the provenance and licenses.

build.rs packs every *.json here, and catalog.toml, into the program.

    python3 fetch_schemas.py
"""

import datetime
import json
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))

SCHEMASTORE = ("Apache-2.0", "https://github.com/SchemaStore/schemastore")

# (file, url, globs, (license, license source))
SCHEMAS = [
    ("compose-spec.json",
     "https://raw.githubusercontent.com/compose-spec/compose-spec/main/schema/compose-spec.json",
     ["**/docker-compose.yml", "**/docker-compose.yaml", "**/docker-compose.*.yml",
      "**/docker-compose.*.yaml", "**/compose.yml", "**/compose.yaml", "**/compose.*.yml",
      "**/compose.*.yaml"],
     ("Apache-2.0", "https://github.com/compose-spec/compose-spec")),
    ("github-workflow.json", "https://json.schemastore.org/github-workflow.json",
     ["**/.github/workflows/*.yml", "**/.github/workflows/*.yaml"], SCHEMASTORE),
    ("github-action.json", "https://json.schemastore.org/github-action.json",
     ["**/action.yml", "**/action.yaml"], SCHEMASTORE),
    ("dependabot-2.0.json", "https://json.schemastore.org/dependabot-2.0.json",
     ["**/.github/dependabot.yml", "**/.github/dependabot.yaml"], SCHEMASTORE),
    ("cargo.json", "https://json.schemastore.org/cargo.json", ["**/Cargo.toml"], SCHEMASTORE),
    ("package.json", "https://json.schemastore.org/package.json", ["**/package.json"], SCHEMASTORE),
    ("tsconfig.json", "https://json.schemastore.org/tsconfig.json",
     ["**/tsconfig.json", "**/tsconfig.*.json", "**/jsconfig.json"], SCHEMASTORE),
    ("gitlab-ci.json",
     "https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json",
     ["**/.gitlab-ci.yml", "**/.gitlab-ci.yaml"],
     ("MIT", "https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE")),
]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "rat-commander fetch_schemas.py"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main():
    rows = []
    catalog = ["# Which files the bundled schemas are for. Generated by fetch_schemas.py.\n"]
    for name, url, globs, (license, source) in SCHEMAS:
        raw = fetch(url)
        json.loads(raw)
        text = raw.decode("utf-8").replace("\r\n", "\n")
        if not text.endswith("\n"):
            text += "\n"
        with open(os.path.join(HERE, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        rows.append((name, url, license, source, len(text)))
        catalog.append("\n[[schema]]\n")
        catalog.append(f'file = "{name}"\n')
        catalog.append(f'url = "{url}"\n')
        catalog.append("files = [" + ", ".join(f'"{g}"' for g in globs) + "]\n")
        print(f"{name}: {len(text)} bytes", file=sys.stderr)
    with open(os.path.join(HERE, "catalog.toml"), "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(catalog))
    apache = fetch("https://www.apache.org/licenses/LICENSE-2.0.txt").decode("utf-8")
    with open(os.path.join(HERE, "LICENSE-APACHE-2.0"), "w", encoding="utf-8", newline="\n") as f:
        f.write(apache.replace("\r\n", "\n"))
    gitlab = fetch("https://gitlab.com/gitlab-org/gitlab/-/raw/master/LICENSE").decode("utf-8")
    with open(os.path.join(HERE, "LICENSE-GITLAB"), "w", encoding="utf-8", newline="\n") as f:
        f.write(gitlab.replace("\r\n", "\n"))
    today = datetime.date.today().isoformat()
    readme = [
        "# JSON Schemas\n\n",
        "These schemas are vendored from where they are published (fetched "
        f"{today} by `fetch_schemas.py`). The editor validates the files named in\n"
        "`catalog.toml` against them; `build.rs` packs them into the program.\n\n",
        "They are separate works, distributed alongside the program under their own\n",
        "licenses, unmodified apart from line endings:\n\n",
        "| File | Source | License |\n| --- | --- | --- |\n",
    ]
    for name, url, license, source, _ in rows:
        readme.append(f"| `{name}` | <{url}> | {license} ([{source}]({source})) |\n")
    readme.append(
        "\nThe Apache License 2.0 text is in `LICENSE-APACHE-2.0`. The GitLab CI schema\n"
        "is part of GitLab, whose license (the schema falls under its MIT Expat terms)\n"
        "is in `LICENSE-GITLAB`.\n"
    )
    with open(os.path.join(HERE, "README.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(readme))


if __name__ == "__main__":
    main()
